version: '3'

services:
  source_postgres:
    image: postgres:latest
    container_name: source_postgres
    ports: 
      - '5433:5432'
    networks:
      - elt_network
    environment:
      - POSTGRES_DB=source_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./source_db_data:/var/lib/postgresql/data

  destination_postgres: 
    image: postgres:latest
    container_name: destination_postgres
    ports: 
      - '5434:5432'
    networks:
      - elt_network
    environment:
      - POSTGRES_DB=destination_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  elt_script:
    build:
      context: ./elt_script # Directory containing the Dockerfile and elt_script.py
      dockerfile: Dockerfile # name of the Dockerfile to use for building the image
    command: []
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres

networks:
  elt_network:
    driver: bridge


  