FROM python:3.9-slim-bookworm

# Install PostgreSQL command-line tools
RUN apt-get update && \
    apt-get install -y wget gnupg2 lsb-release && \
    sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y postgresql-client-16


# Copy the ELT script 
COPY elt_script.py .

# Set the default command to run the ELT script
CMD ["python3", "elt_script.py"]